// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlVQgupyxI2C--zSprfk6gUsIRvivYdkQ',
    appId: '1:546845317104:android:f8acd293d96aea59d12f35',
    messagingSenderId: '546845317104',
    projectId: 'mbappe-fp',
    storageBucket: 'mbappe-fp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYlMHRQzj9bhVBFbz9BqalSncEPNwZMtg',
    appId: '1:546845317104:web:76d07b3060a5456bd12f35',
    messagingSenderId: '546845317104',
    projectId: 'mbappe-fp',
    authDomain: 'mbappe-fp.firebaseapp.com',
    storageBucket: 'mbappe-fp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYlMHRQzj9bhVBFbz9BqalSncEPNwZMtg',
    appId: '1:546845317104:web:76d07b3060a5456bd12f35',
    messagingSenderId: '546845317104',
    projectId: 'mbappe-fp',
    authDomain: 'mbappe-fp.firebaseapp.com',
    storageBucket: 'mbappe-fp.firebasestorage.app',
  );
}
